apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
data:
  AWS_REGION: "us-east-1"
  BOOKS_GRPC_HOST: "books-service:50051"
  BOOKS_PUBLIC_BASE_URL: "http://k8s-default-bookstor-5d55a4b5e7-1138938403.us-east-1.elb.amazonaws.com"
  BOOKS_SERVICE_URL: "http://books-service:5001"
  REVIEWS_SERVICE_URL: "http://reviews-service:5002"
  ORDERS_SERVICE_URL: "http://orders-service:5003"
  USERS_SERVICE_URL: "http://users-service:5004"
  FRONTEND_API_GATEWAY_URL: "/api"
  FRONTEND_USE_MOCKS: "false"
